### ISSUE TITLE
SciPy is not imported, leading to errors in printing results

### ISSUE THREAD

**Issue by bocklund** [lucydot/effmass#1]
`effmass/analysis.py` imports `integrate` by name, however the `mass_integration` function uses the qualified `scipy.integrate.quad`. This leads to an error in line `outputs.print_results(segments[-1], data, settings)`, which fails with the following traceback:

```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-204cc925e032> in <module>()
----> 1 outputs.print_results(segments[-1], data, settings)

~/Projects/joss-reviews/effmass/effmass/outputs.py in print_results(segment, data, settings, polyfit_order)
    136                   polyfit_order=polyfit_order)]))
    137     print("optical mass at band edge (assuming the Kane dispersion) is {:.2f}".
--> 138           format(segment.optical_effmass_kane_dispersion()))
    139 
    140     plt.figure(figsize=(8, 8))

~/Projects/joss-reviews/effmass/effmass/analysis.py in optical_effmass_kane_dispersion(self, fermi_level, temp, alpha, mass_bandedge, upper_limit)
    488             alpha=alpha,
    489             mass_bandedge=mass_bandedge,
--> 490             upper_limit=upper_limit)
    491         bottom = self.weight_integration(
    492             fermi_level=fermi_level,

~/Projects/joss-reviews/effmass/effmass/analysis.py in mass_integration(self, fermi_level, temp, alpha, mass_bandedge, upper_limit)
    334         fermi_level = self.fermi_energy if fermi_level is None else fermi_level
    335 
--> 336         result = scipy.integrate.quad(
    337             self._mass_integrand,
    338             0,

NameError: name 'scipy' is not defined
```

Fixing `scipy.integrate.quad` -> `integrate.quad` should fix this. 

I also suggest writing a test for this code path.

(Part of https://github.com/openjournals/joss-reviews/issues/797)

**Comment by bocklund** [comment]
Also affects the lines where optical mass is calculated in the Jupyter Notebook examples, e.g. `optical_mass_111 = [segments[-6].optical_effmass_kane_dispersion(fermi_level=data.CBM+burstein_moss_kane(x,average_mass,average_alpha),alpha=0.16/ev_to_hartree,mass_bandedge=0.155,upper_limit=0.1) for x in concentrations]`

**Comment by lucydot** [comment]
Thank you for finding this bug @bocklund. I have fixed this as you suggested and have written [a test](https://github.com/lucydot/effmass/blob/a4658d1c200eb3f0f02550efe868d2b4d4b294fc/tests/test_analysis.py#L99-L102)  to catch similar failures in the future.
