### ISSUE TITLE
Inputs doesnt read VASP OUTCAR PROCAR

### ISSUE THREAD

**Issue by hududed** [lucydot/effmass#17]
Hi

I am trying to follow your jupyter demo and gave this input:
```
from effmass import inputs, analysis, extrema, outputs, dos, ev_to_hartree
settings = inputs.Settings(extrema_search_depth=0.075, energy_range=0.25)
data = inputs.Data(r"C:\Users\gr426\PycharmProjects\effmass\OUTCAR",r"C:\Users\gr426\PycharmProjects\effmass\PROCAR", ignore=216)
```

but got this error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\gr426\AppData\Roaming\Python\Python37\site-packages\effmass\inputs.py", line 115, in __init__
    energies[i] = vasp_data.bands[:, 1:].reshape(
TypeError: list indices must be integers or slices, not tuple
```

The OUTCAR and PROCAR files were taken from effmass/tests/data Ge_SP_OUTCAR and Ge_SP_PROCAR.

Are there working sample files that I can try? Please advise.

**Comment by lucydot** [comment]
Hello @hududed,

- Could you try reading in the colinear (cl) or spin-orbit-coupling (soc) `OUTCAR` and `PROCAR` files from the `effmass/tests/data` folder, to see if we can isolate the problem to the spin-polarised case?
- Tests for reading in spin-polarised are passing on Travis here: https://travis-ci.com/lucydot/effmass - can you tell me which version of effmass you are using? support for spin-polarised calculations was introduced in v1.0.0

Lucy

**Comment by hududed** [comment]
Okay, both cl and soc that you mentioned worked. Thanks.
I am currently using the latest v1.0.1.

Now, I am reading from PROCAR of a 2D material e.g. graphene unit cell, but this warning comes up:
```
C:\Users\..\AppData\Roaming\Python\Python37\site-packages\vasppy\procar.py:45: UserWarning: One or more occupancies in your PROCAR file are negative.
  warnings.warn( "One or more occupancies in your PROCAR file are negative." )
C:\Users\..\AppData\Roaming\Python\Python37\site-packages\effmass\inputs.py:151: UserWarning: One or more occupancies in your PROCAR file are negative. All negative occupancies will be set to zero.
  warnings.warn("One or more occupancies in your PROCAR file are negative. All negative occupancies will be set to zero.")
C:\Users\..\AppData\Roaming\Python\Python37\site-packages\effmass\extrema.py:28: UserWarning: You have partial occupation numbers in Data.occupancy. You should check that the attributes Data.VBM, Data.CBM and Data.fermi_energy are correct, and if not, set them manually.
  "You have partial occupation numbers in Data.occupancy. You should check that the attributes Data.VBM, Data.CBM and Data.fermi_energy are correct, and if not, set them manually."
```
which (I assume) then generates an empty segment fields from `segments = extrema.generate_segments(settings,data)`

Are the negative occupancies set to zero the problem?

-Hud
