### ISSUE TITLE
Broken link to notebook from docs

### ISSUE THREAD

**Issue by ajjackson** [lucydot/effmass#2]
The link to the Jupyter example works on the README page, but fails from the homepage of the RTD manual (https://effmass.readthedocs.io/en/latest/). I'm not sure why, as the link in the actual README file looks fine?

My theories are
- there is some strange markdown conversion going on, or 
- you fixed it already and the RTD build is stale.

**Comment by lucydot** [comment]
Thanks for catching this @ajjackson , it was a missing `https://` causing the problem - link from RTD works for me now.
