### ISSUE TITLE
Feature request: Printable representation of Segment

### ISSUE THREAD

**Issue by ajjackson** [lucydot/effmass#3]
It would be nice if Segment objects had a standard printable representation, such as `2.3 eV [0 0 0] -> [1 0 1]`. This can can be implemented by providing a `__str__` method. It would make it easier to keep track of them and work with them interactively. The method implied in the tutorial is to repeatedly call `plot_segments` until you're sure you have the index of the one you want.

**Comment by lucydot** [comment]
Thanks for the suggestion - I've implemented this feature [here](https://github.com/lucydot/effmass/blob/55bfaf9d46d62fd9462dec03663d72cc6b4253b8/effmass/analysis.py#L116-L126) and a usage example is [in the notebook](https://github.com/lucydot/effmass/blob/master/paper/notebook.ipynb) (under 'Generate band segments').
