### ISSUE TITLE
command line interface 

### ISSUE THREAD

**Issue by anovitzkij** [lucydot/effmass#33]
Hey, Lucy. Thank you for this great instrument. Today I was trying to run it via command line. I have performed installation using `pip install effmass` but when I try to run it I got `"effmass" is not recognized as an internal or external command`.
Maybe problem on my side, but other stuff seems to work fine.

**Comment by lucydot** [comment]
Hello, 
If you installed effmass before the CLI was introduced in version 2.0.0 you may need to `pip install --upgrade effmass`. The current version is 2.0.1 - let me know if you are still having problems running the CLI if you are running this version (`pip show effmass` will tell you which version you have). If there are problems it'd be good to know which OS you are using. Thanks - Lucy

**Comment by anovitzkij** [comment]
Upgrade helped! Thank you so much!

Best wishes,
Andrei

**Comment by lucydot** [comment]
Hi @anovitzkij just a reminder that if you have used effmass in any scripts you will need to change `Data` to `DataVasp`. I did The Thing You Should Never Do and broke backwards compatability. But in the long run I think it will be worth it, and I do not think it is used too widely (yet :) ) Lucy
