### ISSUE TITLE
Version number is hard-coded in welcome message

### ISSUE THREAD

**Issue by ajjackson** [lucydot/effmass#46]
The version number message isn't up-to-date with the release numbers.

https://github.com/lucydot/effmass/blob/dac39d404f2417ba0618c8b2183363698ffee69b/effmass/cli.py#L12

I suggest using something like versioneer to keep version numbers centralised.

(This was found by some ASE user/developers.)

**Comment by lucydot** [comment]
Thanks for passing this on - I'll take a look at it later today/this week.
