### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by rightsuman** [lucydot/effmass#51]
Hi Lucy
I am getting this error. The calculation is HSE and the fermi level is inside the conduction band, but there is a gap before the same. 
Can you tell me how to solve this?
I have used both the command line interface as well as your example notebook format. This error comes when I try to load the PROCAR and OUTCAR file. I have used pip for installation.
Reading in data...
Traceback (most recent call last):
  File "/home/suman/.local/bin/effmass", line 8, in <module>
    sys.exit(cli())
  File "/home/suman/.local/lib/python3.8/site-packages/effmass/cli.py", line 87, in cli
    data = inputs.DataVasp(pathname+"/OUTCAR",pathname+"/PROCAR", ignore=int(ignore))
  File "/home/suman/.local/lib/python3.8/site-packages/effmass/inputs.py", line 402, in __init__
    self.check_data(self.spin_channels, self.number_of_kpoints, self.number_of_bands, 
  File "/home/suman/.local/lib/python3.8/site-packages/effmass/inputs.py", line 137, in check_data
    assert (CBM >
AssertionError: The CBM energy is lower than than the VBM energy

**Comment by lucydot** [comment]
Hi @rightsuman - 

Can you send me the files you are using as input?

**Comment by alexey-krasnov** [comment]
Dear Lucy!
I got the same error as @rightsuman, could you please explain, why this error occurs?

**Comment by lucydot** [comment]
Hi @rightsuman just pinging you again - if I don't receive the input files in the next couple of weeks I'll close the issue (feel free to open another one in the future).
